spring:
  application:
    name: tutorials-redis-api
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  data:
    redis:
      client-name: ${spring.application.name}
      host: localhost
      port: 6379
management:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      discovery:
        enabled: false